# ClusterIssuer email address
masterEmail: ""
# 主要工作域名，必填
domain: ""

santorini:
  # 默认则新增，有值则应用; 只要同时设置了 host 则认为使用自配的 mysql
  mysql:
    enable: true
    host: ""
    port: 3306
    username: ""
    password: ""
  # 数据库名称,默认则会自动新建，反之使用即有的
  database: ""
  # 管理员名字，必须提供的
  manager: ""
  # 如果想自行定义host
  host: ""
  # 证书颁发者
  issuerName: ""
  feishu:
    # 飞书应用的 id
    id: ""
    # 飞书应用的 secret
    secret: ""
    # 飞书授权登录回调地址(写在飞书后台的)
    callbackUrl: ""

dashboard:
  # 是否暴露 dashboard 服务
  expose: false
  entrances:
    one:
      # dashboard 访问的域名, 默认是 dashboard.domain
      domain: ""
      # 签发者名字，默认会使用自动生成的签发者，如果域名不在管辖范围就另外找个签发者
      issuerName: ""
    two:
      domain: ""
      issuerName: ""

longhorn:
  # 是否暴露 longhorn 服务
  expose: false
  entrances:
    one:
      # longhorn 访问的域名, 默认是 longhorn.domain
      domain: ""
      # 签发者名字，默认会使用自动生成的签发者，如果域名不在管辖范围就另外找个签发者
      issuerName: ""
    two:
      domain: ""
      issuerName: ""

# 这里的值都可以传递到子 chart 中
# https://news.broadcom.com/app-dev/broadcom-introduces-bitnami-secure-images-for-production-ready-containerized-applications
mysql:
  image:
    repository: bitnamilegacy/mysql