apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # add an annotation indicating the issuer to use.
    {{ include "ingress.certManagerIssuerName" (list . .Values.santorini) }}
    # nginx.ingress.kubernetes.io/canary: "true"
    # nginx.ingress.kubernetes.io/canary-by-header: "sec-fetch-mode"
    # nginx.ingress.kubernetes.io/canary-by-header-value: "navigate"
  name: "{{ include "common.names.fullname" . }}-console-1"
  labels:
    {{- include "common.labels.withoutName" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "ingress.hostName" (list . .Values.santorini "op" ) }}
      secretName: {{ include "ingress.secretName" (list . .Values.santorini "op" ) }}
  rules:
    - host: {{ include "ingress.hostName" (list . .Values.santorini "op" ) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "common.santoriniConsoleFrontendName" . }}
                port:
                  name: http