{{ $defaultIssuerName := (include "santorini.issuer" .) }}
{{- $defaultHost := printf "op.%s" .Values.domain -}}
{{/*# 定义 host 名字*/}}
{{- $hostName := .Values.santorini.host | default $defaultHost -}}
{{- $issuerName := .Values.santorini.issuerName | default $defaultIssuerName -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: {{ $issuerName }}
  name: "{{ include "common.names.fullname" . }}-console-kubernetes"
  namespace: default
  labels:
    {{- include "common.labels.withoutName" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ $hostName }}
      secretName: "{{ include "common.names.fullname" . }}-console-tls"
  rules:
    - host: {{ $hostName }}
      http:
        paths:
          - path: /kubernetes/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubernetes
                port:
                  number: 6443