apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # add an annotation indicating the issuer to use.
    {{ include "ingress.certManagerIssuerName" (list . .Values.santorini) }}
  name: "{{ include "common.names.fullname" . }}-console-kubernetes"
  namespace: default
  labels:
    {{- include "common.labels.withoutName" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "ingress.hostName" (list . .Values.santorini "op" ) }}
      secretName: {{ include "ingress.secretName" (list . .Values.santorini "op" ) }}
  rules:
    - host: {{ include "ingress.hostName" (list . .Values.santorini "op" ) }}
      http:
        paths:
          - path: /kubernetes/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubernetes
                port:
                  number: 6443