apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-santorini-santorini
  labels:
    helm.sh/chart: santorini-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "0.0.1"
subjects:
  - kind: ServiceAccount
    name: release-name-santorini-santorini
roleRef:
  kind: Role
  name: release-name-santorini-santorini
  apiGroup: rbac.authorization.k8s.io