apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-santorini-santorini
  labels:
    helm.sh/chart: santorini-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "0.0.1"