# 初始化容器有 2 个功能
# 1. 检查是否需要建立数据库： 基于上方的配置 主机可通过 docker 指令: 构建一个mysql 环境: docker run -p 13306:3306 --rm --name create-database-test-mysql -d -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=op mysql:8.0.27
# 2. 兼容之前的 JAVA_OPTS 为环境唯一要求的经典 boot 镜像组
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.santoriniConsoleBackendName" . }}
  labels:
    app.kubernetes.io/name: {{ include "common.santoriniConsoleBackendName" . }}
    {{- include "common.labels.withoutName" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.santoriniConsoleBackendName" . }}
      {{- include "common.matchLabels.withoutName" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.santoriniConsoleBackendName" . }}
        {{- include "common.labels.withoutName" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "common.santoriniName" . }}
      {{- with .Values.santorini.tolerations }}
      tolerations:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: shared-data
          emptyDir: { }
      initContainers:
        - name: init-db
          image: {{ template "child.mysql.image" . }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                optional: false
                name: {{ include "common.santoriniName" . }}
            - secretRef:
                optional: false
                name: {{ include "common.santoriniName" . }}    
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.mysqlName" . }}
                  key: mysql-root-password
                  optional: true
          command:
            - sh
            - -c
            - |
              echo "Running init SQL...MYSQL_CREATE_USERNAME:${MYSQL_CREATE_USERNAME},MYSQL_CREATE_DATABASE:${MYSQL_CREATE_DATABASE}"
              export SQL_C="CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
              export SQL_G="GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';"
              if [ ${MYSQL_CREATE_DATABASE} = "true" ]; then mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME --port=$MYSQL_PORT -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"; fi
              if [ ${MYSQL_CREATE_USERNAME} = "true" ]; then mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME --port=$MYSQL_PORT -p${MYSQL_ROOT_PASSWORD} -e "$SQL_C"; fi
              if [ ${MYSQL_CREATE_USERNAME} = "true" ]; then mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME --port=$MYSQL_PORT -p${MYSQL_ROOT_PASSWORD} -e "$SQL_G"; fi
        
      containers:
        #  ctr -n k8s.io image import --base-name “santorini-console-backend:latest” /root/jib-image.tar
        #  docker image load -i /root/jib-image.tar
        #  docker run --rm -d --name santorini-console-backend -p 8080:8080 santorini-console-backend:latest
        - name: console-backend
          image: {{ template "backend.image" . }}
          imagePullPolicy: {{ .Values.santorini.backend.image.pullPolicy | quote }}
          envFrom:
            - configMapRef:
                optional: false
                name: {{ include "common.santoriniName" . }}
            - secretRef:
                optional: false
                name: {{ include "common.santoriniName" . }}
          env:
            {{- if .Values.santorini.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.santorini.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
          {{- if .Values.santorini.backend.resources }}
          resources: {{- toYaml .Values.santorini.backend.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.santorini.healthCheck.livenessProbe.enabled }}
          livenessProbe:
            {{- if eq .Values.santorini.healthCheck.type "http" }}
            httpGet:
              path: {{ .Values.santorini.healthCheck.livenessProbe.httpPath }}
              port: {{ .Values.santorini.healthCheck.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.santorini.healthCheck.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.santorini.healthCheck.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.santorini.healthCheck.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.santorini.healthCheck.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.santorini.healthCheck.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.santorini.healthCheck.livenessProbe.failureThreshold }}
          {{- else if .Values.santorini.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.santorini.healthCheck.readinessProbe.enabled }}
          readinessProbe:
            {{- if eq .Values.santorini.healthCheck.type "http" }}
            httpGet:
              path: {{ .Values.santorini.healthCheck.readinessProbe.httpPath }}
              port: {{ .Values.santorini.healthCheck.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.santorini.healthCheck.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.santorini.healthCheck.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.santorini.healthCheck.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.santorini.healthCheck.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.santorini.healthCheck.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.santorini.healthCheck.readinessProbe.failureThreshold }}
          {{- else if .Values.santorini.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.santorini.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: shared-data
              mountPath: /work
        {{- if .Values.santorini.debugWithShell }}
        - name: jshell
          image: jshell-auto-v2:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: shared-data
              mountPath: /work
          command:
            - sh
            - -c
            - |
              sleep 360000
        {{- end }}
