{{/* 并非 pod,而是人; 管理员的角色 */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 这里扮演的是管理员
  name: {{ include "common.santoriniManager" . }}
  labels:
    santorini.io/role: manager
    {{- include "common.labels.withoutName" . | nindent 4 }}
rules:
  # 这里算是直接部署资源
  - apiGroups: [ "apps" ]
    resources: [ "deployments","deployments/newreplicaset" ]
    resourceNames: [ ]
    verbs: [ "create","update","get", "list","delete","patch" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    resourceNames: [ ]
    verbs: [ "create","update","get","list","delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    resourceNames: [ ]
    verbs: [ "create","update","get","delete","list" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ ]
    verbs: [ "list" ]
    # 间接部署资源
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    resourceNames: [ ]
    verbs: [ "list","get","delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods","pods/log" ]
    resourceNames: [ ]
    verbs: [ "list","get" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    resourceNames: [ ]
    verbs: [ "list","get","create" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    resourceNames: [ ]
    verbs: [ "list" ]
  - apiGroups: [ "autoscaling" ]
    resources: [ "horizontalpodautoscalers" ]
    resourceNames: [ ]
    verbs: [ "list","get","create", "update", "delete", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    resourceNames: [ ]
    verbs: [ "create","list" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ "loongcollector-secret" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ ]
    verbs: [ "create","list" ]
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets" ]
    resourceNames: [ "loongcollector-ds" ]
    verbs: [ "get" ]
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets" ]
    resourceNames: [ ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    resourceNames: [ ]
    verbs: [ "list","get" ]
