apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 这里扮演的是pod
  name: {{ include "common.santoriniName" . }}
  labels:
    {{- include "common.labels.withoutName" . | nindent 4 }}
rules:
  - apiGroups: [ "apiregistration.k8s.io" ]
    resources: [ "*" ]
    resourceNames: [ ]
    verbs: [ "get", "list", "watch"]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "*" ]
    resourceNames: [ ]
    verbs: [ "get", "list", "watch"]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "rolebindings" ]
    resourceNames: [ ]
    verbs: [ "get", "list", "watch", "create", "update", "delete" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles" ]
    resourceNames: [ ]
    verbs: [ "get", "list", "watch", "create", "update", "delete" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterroles" ]
    resourceNames: [ ]
    verbs: [ "list","get" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterrolebindings" ]
    resourceNames: [ ]
    verbs: [ "get", "list", "watch", "create", "update", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ ]
    verbs: [ "get","create","update","patch","delete","deletecollection" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ ]
    verbs: [ "get","create","update","patch","delete","deletecollection" ]
