apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-santorini-santorini
  annotations:
    "meta.helm.sh/release-namespace": kube-santorini
    "meta.helm.sh/release-name": release-name
  labels:
    helm.sh/chart: santorini-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "0.0.1"
data:
  mysql-database: "santorini"
  # 这里使用的是内置的 mysql
  mysql-host: "release-name-mysql"
  mysql-port: "3306"
  mysql-root-username: "root"
  mysql-username: "santorini"
  mysql-create-username: "true"
  mysql-create-database: "true"