{{/* 并非 pod,而是人; 管理员的角色 */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # 这里扮演的是管理员
  name: {{ include "common.santoriniManager" . }}
  labels:
    santorini.io/role: manager
    {{- include "common.labels.withoutName" . | nindent 4 }}
rules:
  - apiGroups: [ "*" ]
    resources: [ "pods","replicasets","deployments" ]
    resourceNames: [ ]
    verbs: [ "get","list" ]