{{/* 并非 pod,而是人; 管理员的角色 */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 这里扮演的是管理员
  name: {{ include "common.santoriniManager" . }}
  labels:
    santorini.io/role: manager
    {{- include "common.labels.withoutName" . | nindent 4 }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    resourceNames: [ ]
    verbs: [ "create","update" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    resourceNames: [ ]
    verbs: [ "create","update","get","delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    resourceNames: [ ]
    verbs: [ "create","update","get","delete","list" ]