apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 这里扮演的是普通用户
  name: {{ include "common.santoriniUser" . }}
  labels:
    santorini.io/role: user
    {{- include "common.labels.withoutName" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    resourceNames: [ ]
    verbs: [ "list" ]