apiVersion: v2
name: santorini
description: santorini for Kubernetes

type: application

version: 0.2.0
appVersion: "0.2.0"

dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
  # 因为 CRD 的问题，这个必须自行安装
  # - name: cert-manager
  #   version: "~1.19.1"
  #   repository: "https://charts.jetstack.io"
  - name: mysql
    version: "~14.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: santorini.mysql.enable